[package]
name = "pathfinder"
version = "0.1.0"
edition = "2021"
authors = ["JuniperFuchs <https://github.com/JuniperFuchs>"]
description = "Pathfinder Application"

[package.metadata.deb]
maintainer = "JuniperFuchs <https://github.com/JuniperFuchs/Pathfinder>"
extended-description = "A pathfinding tool written in Rust."
section = "utility"
priority = "optional"
assets = [
    ["target/release/visual_pathfinder", "usr/bin/visual_pathfinder", "755"],
]

[dependencies]
macroquad = "0.4"