[package]
name = "Pathfinder"
version = "0.1.0"
edition = "2021"
authors = ["JuniperFuchs <https://github.com/JuniperFuchs>"]
description = "Pathfinder Visualizer Application"

[package.metadata.deb]
maintainer = "JuniperFuchs <https://github.com/JuniperFuchs/Pathfinder>"
extended-description = "A visual pathfinding tool written in Rust."
section = "utility"
priority = "optional"
assets = [
    ["target/release/Pathfinder", "usr/bin/Pathfinder", "755"],
]

[dependencies]
macroquad = "0.4"